---
version: 2

sphinx:
    configuration: doc/source/conf.py

formats: all

python:
   install:
      - method: pip
        path: .
        extra_requirements:
           - docs

build:
  os: ubuntu-22.04
  tools:
    python: "3"
